language: go
go:
    - 1.5
    - 1.6
    - tip
install:
      - go get -u google.golang.org/grpc
      - go get -u github.com/golang/protobuf
      - go get github.com/xackery/gobeam
      - go get -v .